/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface USTravelHistory {
	travelEvents?: USTravelEvent[];
	lastLeftHomeCountry?: string;
	i94Number?: string;
	dateStatusExpires?: string;
}
export interface USTravelEvent {
	date?: string;
	place?: string;
	status?: string;
}
export interface UserData {
	applicantInfo?: ApplicantInfo;
	usTravelHistory?: USTravelHistory;
	isMarried?: boolean;
	spouseInfo?: SpouseInfo;
	childInfo?: ChildInfo[];
	lastAddressBeforeUS?: object;
	lastAddressPersecuted?: object;
	/**
	 * The applicant's places of residence for the past 5 years.
	 */
	residencesInLastFiveYears?: AddressWithDates[];
	/**
	 * List of schools attended by applicant.
	 */
	educationInfo?: SchoolInfo[];
	/**
	 * List of applicant's employment history for past 5 years.
	 */
	employmentInfo?: EmploymentInfo[];
	motherInfo?: RelativeInfo;
	fatherInfo?: RelativeInfo;
	siblingInfo?: RelativeInfo[];
	/**
	 * Why are you applying for asylum or withholding of removal under section 241(b)(3) of the INA, or for withholding of removal under the Convention Against Torture?
	 */
	whyApplying?: string[];
	experiencedHarm?: object;
	fearsHarm?: object;
	arrestedInOtherCountry?: object;
	organizationInfo?: object;
	afraidOfTorture?: object;
	relativeAppliedForAsylum?: object;
	otherCountryApplications?: OtherCountryApplications;
	causedHarm?: object;
	returnCountry?: object;
	applyAfterOneYear?: object;
	crimeInUS?: object;
	relativeHelpPrepare?: RelativeHelpPrepare;
}

export interface SpouseInfo {
	lastName?: string;
	firstName?: string;
	middleName?: string;
	aliases?: string[];
	dateOfBirth?: string;
	alienRegistrationNumber?: string;
	socialSecurityNumber?: string;
	passportNumber?: string;
	dateOfMarriage?: string;
	placeOfMarriage?: string;
	cityOfBirth?: string;
	countryOfBirth?: string;
	nationality?: string;
	raceEthnicOrTribalGroup?: string;
	gender?: 'MALE' | 'FEMALE';
	inUS?: boolean;
	locationInUS?: string;
	placeOfLastEntry?: string;
	dateOfLastEntry?: string;
	i94Number?: string;
	immigrationStatusWhenLastAdmitted?: string;
	currentImmigrationStatus?: string;
	statusExpirationDate?: string;
	isInImmigrationCourt?: boolean;
	previousArrivalDate?: string;
	includeInApplication?: boolean;
}
export interface SchoolInfo {
	schoolName?: string;
	typeOfSchool?: string;
	address?: string;
	fromDate?: string;
	toDate?: string;
}
export interface RelativeInfo {
	fullName?: string;
	cityOrTownOfBirth?: string;
	countryOfBirth?: string;
	currentLocation?: string;
	isDeceased?: boolean;
}
export interface RelativeHelpPrepare {
	didRelativeHelp?: 'YES' | 'NO';
	firstRelative?: Relative;
	secondRelative?: Relative;
}
export interface Relative {
	name?: string;
	relationship?: string;
}
export interface QuestionWithExplanation {
	yesNoAnswer?: 'YES' | 'NO';
	explanation?: string;
}
export interface OtherCountryApplications {
	travelThroughOtherCountry?: 'YES' | 'NO';
	applyOtherCountry?: 'YES' | 'NO';
	explanation?: string;
}
export interface OrganizationInfo {
	associatedWithOrganizations?: QuestionWithExplanation;
	continueToParticipate?: QuestionWithExplanation;
}
export interface MailingAddress {
	inCareOf?: string;
	streetName?: string;
	streetNumber?: string;
	apartmentNumber?: string;
	city?: string;
	state?: string;
	zipCode?: string;
	areaCode?: string;
	phoneNumber?: string;
}
export interface EmploymentInfo {
	employerName?: string;
	employerAddress?: string;
	applicantOccupation?: string;
	fromDate?: string;
	toDate?: string;
}
export interface ChildInfo {
	lastName?: string;
	firstName?: string;
	middleName?: string;
	dateOfBirth?: string;
	alienRegistrationNumber?: string;
	socialSecurityNumber?: string;
	passportNumber?: string;
	maritalStatus?: 'SINGLE' | 'MARRIED' | 'DIVORCED' | 'WIDOWED';
	cityOfBirth?: string;
	countryOfBirth?: string;
	nationality?: string;
	raceEthnicOrTribalGroup?: string;
	gender?: 'MALE' | 'FEMALE';
	inUS?: boolean;
	/**
	 * Only required if child is not in US.
	 */
	location?: string;
	placeOfLastEntry?: string;
	dateOfLastEntry?: string;
	i94Number?: string;
	immigrationStatusWhenLastAdmitted?: string;
	currentImmigrationStatus?: string;
	statusExpirationDate?: string;
	isInImmigrationCourt?: boolean;
	includeInApplication?: boolean;
}
export interface ApplicantInfo {
	lastName?: string;
	firstName?: string;
	middleName?: string;
	aliases?: string[];
	usResidence?: MailingAddress;
	usMailingAddress?: MailingAddress;
	gender?: 'MALE' | 'FEMALE';
	maritalStatus?: 'SINGLE' | 'MARRIED' | 'DIVORCED' | 'WIDOWED';
	dateOfBirth?: string;
	cityOfBirth?: string;
	countryOfBirth?: string;
	presentNationality?: string;
	nationalityAtBirth?: string;
	raceEthnicOrTribalGroup?: string;
	religion?: string;
	nativeLanguage?: string;
	fluentInEnglish?: boolean;
	otherLanguages?: string[];
	alsoApplyingConventionAgainstTorture?: boolean;
	alienRegistrationNumber?: string;
	socialSecurityNumber?: string;
	uscisAccountNumber?: string;
	immigrationCourtHistory?: 'NEVER' | 'CURRENTLY' | 'NOT_NOW_BUT_IN_THE_PAST';
	countryWhoLastIssuedPassport?: string;
	passportNumber?: string;
	travelDocumentNumber?: string;
	travelDocumentExpirationDate?: string;
}
export interface AddressWithDates {
	streetName?: string;
	streetNumber?: string;
	cityOrTown?: string;
	departmentProvinceOrState?: string;
	country?: string;
	fromDate?: string;
	toDate?: string;
}

