from data_types import *
from i_589_page_1 import *
from i_589_page_2 import *
from i_589_page_3 import *
from i_589_page_4 import *
from i_589_page_5 import *
from i_589_page_6 import *
from i_589_page_7 import *
from i_589_page_8 import *
from i_589_page_9 import *
from i_589_page_10 import *
from i_589_page_11 import *
from i_589_page_12 import *
from datetime import date
from form import Form

page_1 = Page_1(True,
                "A1B2",
                "C3D4",
                "E5F6",
                "Michael",
                "Charles",
                "Kreisel",
                ["Homer Simpson",
                 "Wolfgang A. Mozart"],
                "1829 Monroe St NE",
                "457",
                "Washington",
                "DC",
                "20018",
                "5555555555",
                "Laura Kreisel",
                "1234567890",
                "1829 Monroe St NE",
                "457",
                "Washington",
                "DC",
                "20018",
                Gender.MALE,
                MaritalStatus.MARRIED,
                date(2017, 5, 20),
                "Woodbridge",
                "USA",
                "US",
                "US",
                "White",
                "NA",
                ImmigrationCourtStatus.NEVER,
                date(2018, 6, 20),
                "NA",
                UsEntry(date(2018, 10, 5), "Baltimore, MD", "Visitor", date(2020, 10, 23)),
                "US",
                date(2022, 12, 17),
                "English",
                False,
                ["Klingon", "Esperanto"],
                "AX394F5",
                "PPQQSTY35",
                UsEntry(date(2017, 4, 1), "Topeka, KS", "Visitor"),
                UsEntry(date(2015, 7, 10), "Tuscaloosa, OK", "Visitor"))

page_2 = Page_2(False, 
                "1982536", 
                "K32FG89", 
                date(1987, 12, 25), 
                "CX76MN",
                "Johnson",
                "Lyndon",
                "Baines",
                ["LBJ", "Landslide Lyndon"],
                date(1956, 1, 2),
                "Yosemite Valley, CA",
                "Stonewall, TX",
                "USA",
                "USA",
                "White",
                Gender.FEMALE,
                True,
                "Tajikhistan",
                UsEntry(date(2017, 4, 1), "Topeka, KS", "Visitor", date(2017, 4, 1)),
                "90248742",
                "Visitor",
                False,
                date(2016, 8, 10),
                False,
                True,
                4,
                ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Denmark",
                    "None",
                    "Reindeer",
                    Gender.MALE,
                    True,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    True,
                    False))

page_3 = Page_3(ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Denmark",
                    "None",
                    "Reindeer",
                    Gender.FEMALE,
                    True,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    False,
                    True), 
                    ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Denmark",
                    "None",
                    "Reindeer",
                    Gender.MALE,
                    False,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    True,
                    False),
                    ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Denmark",
                    "None",
                    "Reindeer",
                    Gender.FEMALE,
                    True,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    False,
                    True))

page_4 = Page_4(AddressFields("123", 
                              "Mulberry St.", 
                              "Lancaster", 
                              "Pennsylvania", 
                              "USA", 
                              date(2015, 1, 1),
                              date(2016, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                AddressFields("456", 
                              "Cranberry St.", 
                              "Lanclesburg", 
                              "New Jersey", 
                              "UK", 
                              date(2016, 1, 1),
                              date(2017, 2, 4)),
                SchoolFields("Amherst College",
                             "College",
                             "Amherst College, Amherst, MA 01002",
                             date(2006, 9, 1),
                             date(2010, 5, 1)),
                SchoolFields("Amherst College",
                             "College",
                             "Amherst College, Amherst, MA 01002",
                             date(2006, 9, 1),
                             date(2010, 5, 1)),
                SchoolFields("Amherst College",
                             "College",
                             "Amherst College, Amherst, MA 01002",
                             date(2006, 9, 1),
                             date(2010, 5, 1)),
                SchoolFields("Amherst College",
                             "College",
                             "Amherst College, Amherst, MA 01002",
                             date(2006, 9, 1),
                             date(2010, 5, 1)),
                EmployerFields("Rutgers University, New Brunswick, NJ",
                               "Research Assistant",
                               date(2005, 6, 1),
                               date(2007, 9, 1)),
                EmployerFields("Rutgers University, New Brunswick, NJ",
                               "Research Assistant",
                               date(2005, 6, 1),
                               date(2007, 9, 1)),
                EmployerFields("Rutgers University, New Brunswick, NJ",
                               "Research Assistant",
                               date(2005, 6, 1),
                               date(2007, 9, 1)),
                RelativeFields("Mary Mac", "Kyoto", "Japan", "Japan", True),
                RelativeFields("Harry Hac", "Tokyo", "Japan", "Japan", True),
                RelativeFields("Harry Hac", "Tokyo", "Japan", "Japan", True),
                RelativeFields("Harry Hac", "Tokyo", "Japan", "Japan", True),
                RelativeFields("Harry Hac", "Tokyo", "Japan", "Japan", True),
                RelativeFields("Harry Hac", "Tokyo", "Japan", "Japan", True))

page_5 = Page_5([AsylumReason.RACE, 
                 AsylumReason.RELIGION, 
                 AsylumReason.NATIONALITY, 
                 AsylumReason.POLITICAL,
                 AsylumReason.SOCIAL,
                 AsylumReason.TORTURE],
                 True,
                 "Explanation here.",
                 True,
                 "Explanation here.")

page_6 = Page_6(True, 
                "Explanation here.",
                True, 
                "Explanation here.",
                True, 
                "Explanation here.",
                True, 
                "Explanation here.")

page_7 = Page_7(True, 
                "Explanation here",
                True,
                True,
                "Explanation here.",
                False,
                "Explanation here.")

page_8 = Page_8(True,
                "Explanation here.",
                True,
                "Explanation here.",
                False,
                "Explanation here.")

page_9 = Page_9()

page_10 = Page_10()

page_11 = Page_11("1928374", 
                  "Pancho Gonzalez", 
                  date(2018,11,30), 
                  ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Denmark",
                    "None",
                    "Reindeer",
                    Gender.FEMALE,
                    True,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    False,
                    True),
                  ChildFields(
                    "123456",
                    "74280429",
                    MaritalStatus.MARRIED,
                    "0123456789",
                    "Reindeer",
                    "Rudolph",
                    "Red Nose",
                    date(1932, 12, 25),
                    "North Pole",
                    "Dencanussia",
                    "None",
                    "Reindeer",
                    Gender.MALE,
                    True,
                    "North Pole",
                    UsEntry(date(2018, 12, 25), "New York, NY", "Entered Without Inspection", date(2018, 12, 25)),
                    "34F66",
                    "Entered Without Inspection",
                    True,
                    False))

page_12 = Page_12("1928374", 
                  "Pancho Gonzalez", 
                  date(2018,11,30),
                  "A.I.",
                  "13",
                  "Some text to explain what's going on á, é, í, ó, ú, ü, ñ, ¿, ¡ ひ")
pages = [page_1, page_2, page_3, page_4, page_5, page_6, page_7, page_8, page_9, page_10, page_11, page_12]
form = Form(pages)
output = form.assemble()
with open("page-test.pdf", 'wb') as out:
    output.write(out)
